# Build stage
FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o calc main.go

# Final stage
FROM alpine
WORKDIR /app
COPY --from=builder /app/calc .
ENTRYPOINT ["/app/calc"]
